apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-thynkr-config
  namespace: prod
data:
  ENV_NM: "prod"
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  
  # AWS Configuration
  AWS_REGION: "us-east-1"
  BEDROCK_REGION: "us-east-1"
  
  # LLM Models
  BEDROCK_MODEL_CLAUDE: "anthropic.claude-3-5-sonnet-20241022-v2:0"
  BEDROCK_MODEL_TITAN: "amazon.titan-embed-text-v1"
  
  # LLM Parameters
  MAX_TOKENS: "4000"
  TEMPERATURE: "0.1"
  TOP_P: "0.9"
  
  # ChromaDB Configuration
  CHROMA_HOST: "chromadb-service.prod.svc.cluster.local"
  CHROMA_PORT: "8000"
  CHROMA_COLLECTION_NAME: "aecad_context"
  
  # Redis Configuration
  REDIS_DB: "0"
  
  # Context Management
  SESSION_TIMEOUT: "3600"
  MAX_CONTEXT_LENGTH: "50000"
  CONTEXT_WINDOW_SIZE: "10"
  
  # Service URLs
  FILE_MGMT_SERVICE_URL: "http://backend-filemgmt-service.prod.svc.cluster.local:80"
  CORE_SERVICE_URL: "http://backend-core-service.prod.svc.cluster.local:80"
  
  # Confidence Thresholds
  LOW_CONFIDENCE_THRESHOLD: "0.7"
  HIGH_CONFIDENCE_THRESHOLD: "0.9"
  CONSENSUS_THRESHOLD: "0.6"
  
  # Performance Settings
  MAX_CONCURRENT_REQUESTS: "10"
  REQUEST_TIMEOUT: "30"
  RETRY_ATTEMPTS: "3"