apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-thynkr
  namespace: prod
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: aecad-thynkr-secrets
        objectType: secretsmanager
        jmesPath:
          - path: "AWS_ACCESS_KEY_ID"
            objectAlias: "AWS_ACCESS_KEY_ID"
          - path: "AWS_SECRET_ACCESS_KEY"
            objectAlias: "AWS_SECRET_ACCESS_KEY"
          - path: "REDIS_URL"
            objectAlias: "REDIS_URL"
          - path: "REDIS_PASSWORD"
            objectAlias: "REDIS_PASSWORD"
          - path: "BEDROCK_ACCESS_KEY"
            objectAlias: "BEDROCK_ACCESS_KEY"
          - path: "BEDROCK_SECRET_KEY"
            objectAlias: "BEDROCK_SECRET_KEY"
  secretObjects:
    - secretName: aecad-thynkr-secrets
      type: Opaque
      data:
        - key: AWS_ACCESS_KEY_ID
          objectName: "AWS_ACCESS_KEY_ID"
        - key: AWS_SECRET_ACCESS_KEY
          objectName: "AWS_SECRET_ACCESS_KEY"
        - key: REDIS_URL
          objectName: "REDIS_URL"
        - key: REDIS_PASSWORD
          objectName: "REDIS_PASSWORD"
        - key: BEDROCK_ACCESS_KEY
          objectName: "BEDROCK_ACCESS_KEY"
        - key: BEDROCK_SECRET_KEY
          objectName: "BEDROCK_SECRET_KEY"